version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: jaffle_shop.customers
      - name: jaffle_shop.orders
      - name: stripe.payment

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique
